// Auto-generated by OpenLane
module viterbi_decoder(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input en,
  input[15:0] data,
  output[7:0] data_out,
  output done_flag
);
endmodule
